# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Eh.Modpack
PackageVersion: 1.0.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ehmodpack.exe
  PortableCommandAlias: ehmodpack
UpgradeBehavior: install
Commands:
- ehmodpack
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ehshit/ehmodpack/releases/download/v1.0.2/ehmodpack-windows-x86_64.zip
  InstallerSha256: B5605612811D7BC785887AFA0BA93D6678EDB9B36D2B38FD13F055A7F7B28C60
ManifestType: installer
ManifestVersion: 1.12.0
